name: stampede_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.12.1=h00a0c3c_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - dav1d=1.2.1=h2bbff1b_0
  - eigen=3.4.0=h59b6b97_0
  - expat=2.7.1=h8ddb27b_0
  - ffmpeg=6.1.1=h9b0fb35_4
  - filelock=3.17.0=py310haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fsspec=2025.7.0=py310hbc747e5_0
  - gflags=2.2.2=hd77b12b_1
  - giflib=5.2.2=h7edc060_0
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=ha00e802_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - importlib-metadata=8.5.0=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libprotobuf=5.29.3=h65a231f_1
  - libtheora=1.2.0=habf309d_1
  - libtiff=4.7.0=h404307b_0
  - libtorch=2.5.1=cpu_mkl_h9002858_104
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - numpy=2.0.1=py310h055cbcc_1
  - numpy-base=2.0.1=py310h65a83cf_1
  - opencv=4.10.0=py310h28596fa_7
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.0.18=h543e019_0
  - opentelemetry-api=1.37.0=py310haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.1.0=py310hea0d53e_1
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - python=3.10.18=h981015d_0
  - pytorch=2.5.1=cpu_mkl_py310h0452e45_104
  - qtbase=6.7.3=hd088775_4
  - setuptools=80.9.0=py310haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - sqlite=3.50.2=hda9a48d_1
  - sympy=1.14.0=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - torchaudio=2.5.1=py310hc64d2fc_0
  - torchvision=0.20.1=cpu_py310h99a9fa7_2
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zipp=3.21.0=py310haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - idna==3.11
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - packaging==25.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - psutil==7.1.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.15.3
      - six==1.17.0
      - ultralytics==8.3.213
      - ultralytics-thop==2.0.17
      - urllib3==2.5.0
prefix: E:\Anaconda\envs\stampede_env
